import turtle

def smile():
    turtle.begin_fill()
    for i in range(45):
        turtle.forward(20)
        turtle.right(8)
    turtle.color("yellow")
    turtle.end_fill()
    turtle.color("black")
    turtle.penup()
    turtle.goto(-65, -95)
    turtle.pendown()
    turtle.begin_fill()
    for i in range(45):
        turtle.forward(4)
        turtle.right(8)
    turtle.color("white")
    turtle.end_fill()
    turtle.color("black")
    turtle.penup()
    turtle.goto(0,0)
    turtle.goto(65, -95)
    turtle.pendown()
    turtle.begin_fill()
    for i in range(45):
        turtle.forward(4)
        turtle.right(8)
    turtle.color("white")
    turtle.end_fill()
    turtle.color("black")
    turtle.penup()
    turtle.goto(0, 0)
    turtle.goto(60, -115)
    turtle.pendown()
    turtle.begin_fill()
    for i in range(45):
        turtle.forward(2.5)
        turtle.right(8)
    turtle.color("brown")
    turtle.end_fill()
    turtle.color("black")
    turtle.penup()
    turtle.goto(0, 0)
    turtle.goto(-60, -115)
    turtle.pendown()
    turtle.begin_fill()
    for i in range(45):
        turtle.forward(2.5)
        turtle.right(8)
    turtle.color("brown")
    turtle.end_fill()
    turtle.color("black")
    turtle.penup()
    turtle.goto(0, 0)
    turtle.goto(-60, -125)
    turtle.pendown()
    turtle.begin_fill()
    for i in range(45):
        turtle.forward(1.2)
        turtle.right(8)
    turtle.color("black")
    turtle.end_fill()
    turtle.color("black")
    turtle.penup()
    turtle.goto(0, 0)
    turtle.goto(60, -125)
    turtle.pendown()
    turtle.begin_fill()
    for i in range(45):
        turtle.forward(1.2)
        turtle.right(8)
    turtle.color("black")
    turtle.end_fill()
    turtle.color("black")
    turtle.penup()
    turtle.goto(0,0)
    turtle.goto(-65, -200)
    turtle.pendown()
    turtle.right(45)
    for i in range(25):
        turtle.forward(7)
        turtle.right(-3.5)
    turtle.left(90)
    for i in range(10):
        turtle.forward(1)
        turtle.right(1)
    for i in range(15):
        turtle.forward(-1)
        turtle.right(-1)
    turtle.penup()
    turtle.goto(0,0); turtle.goto(-65, -200)
    turtle.pendown()
    turtle.right(90)
    for i in range(10):
        turtle.forward(1)
        turtle.right(-1)
    for i in range(15):
        turtle.forward(-1)
        turtle.right(1)
    turtle.penup()
    turtle.goto(0, 0)
    turtle.pendown()
smile()

input()